### PR TITLE
Add crispr session

### PR DESCRIPTION
**Pull request by mblue9**
Not sure if I've added this right so if I need to make changes just let me know.

I put TBA for the video links til I have the link codes to add.

I put the FAQ link as https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/crispr-screen/faqs/ is that right or should it be a Google doc?

### CODE REVIEW

**Comment by hexylena** [comment]
Wow you got it almost right, no one else has tried to contribute these yet :) I can take it from here.

Edit: ah bugger, I lost track of your video because it was via email, I'm uploading it now. I should've had captions to you already, I'm sorry.

- we'll fix the links when I get them all uploaded (we'll upload both to youtube)
- and for the FAQ you dont' need a link, we've decided we'll skip linking FAQs here, and then just direct people to checking it in the materials / supporting information.

**Comment by mblue9** [comment]
Ok great, thanks a lot @hexylena  🙏 !

**Comment by hexylena** [comment]
Nope it's all automated! The bot will run and create the channel, setup the
bookmarks, and link it from the site!

**Comment by mblue9** [comment]
Oh great!

**Comment by hexylena** [comment]
I'll go ahead and merge this now with the expectation of corrected captions before tapas starts :)

**Pull request merged**
