### PR TITLE
fix wrong link

### PR DESCRIPTION
**Pull request by mblue9**
sorry I had put the wrong link

### CODE REVIEW

**Comment by mblue9** [comment]
Sorry to bother, would it be possible to merge this as hoping to send the page to the instructors today

**Comment by hexylena** [comment]
sorry sincere apologies, have been giving a workshop all week.

**Comment by hexylena** [comment]
I have invited you, please feel free to merge your own PRs especially if they're passing tests :)

**Comment by mblue9** [comment]
Thanks! And no apology necessary, I didn't give much notice :) Hope your workshop went well!

**Pull request merged**
