### PR TITLE
Add speakers for videos and tweaks

### PR DESCRIPTION
**Pull request by mblue9**
a few edits

### CODE REVIEW

**Comment by mblue9** [comment]
Just noting the fail in the actions here is due to an expired certificate & I don't know how to fix that

```
Run ruby/setup-ruby@v1
Modifying PATH
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.0.[5](https://github.com/gallantries/video-library/actions/runs/4515215972/jobs/7952232423?pr=74#step:3:6)-ubuntu-22.04.tar.gz
  certificate has expired
  Waiting 14 seconds before trying again
  certificate has expired
  Waiting 14 seconds before trying again
  Took  2[8](https://github.com/gallantries/video-library/actions/runs/4515215972/jobs/7952232423?pr=74#step:3:10).17 seconds
Error: Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:[9](https://github.com/gallantries/video-library/actions/runs/4515215972/jobs/7952232423?pr=74#step:3:11)46:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:[12](https://github.com/gallantries/video-library/actions/runs/4515215972/jobs/7952232423?pr=74#step:3:14))
```

**Comment by hexylena** [comment]
Thanks for the PR @mblue9 i'll look into the error.

**Comment by hexylena** [comment]
https://github.com/ruby/setup-ruby/issues/487 sounds like it'll be fixed now.

@mblue9 also do you want to add your speakers to a 'bioc' affiliation?

**Comment by hexylena** [comment]
> I'd been wondering that. Could they go to a bioconductor channel & we see how that goes, and then if it looks like it's needed we make separate channels? But are certificates possible for these tutorials from the bot and if so would the tutorials need separate channels?

Yes, we can play it by ear, splitting as needed.

Regarding the certificate bot, ok, we'll need to figure something out there.

**Comment by mblue9** [comment]
Ok great. 
I see this is failing now due to missing `date:`values  https://github.com/gallantries/video-library/actions/runs/4531238085/jobs/7981147767?pr=74
Those tuts have no video should I add today's date or something else?

**Comment by hexylena** [comment]
We will fix it.

**Comment by hexylena** [comment]
I think this looks good, let's ship it for now

**Pull request merged**
